use anyhow::{Context, Result};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;

const POST_COMMIT_SCRIPT: &str = r#"#!/bin/sh
# Auto-generated by 'mt agent-config bootstrap'
# Syncs agent-configs to ~/.cursor/, ~/.claude/, ~/.config/opencode/ when agent-configs/ changes

changed_files=$(git diff-tree --no-commit-id --name-only -r HEAD)

if echo "$changed_files" | grep -q "^agent-configs/"; then
    echo "Detected changes in agent-configs/, syncing..."
    mt agent-config sync
fi
"#;

pub fn run() -> Result<()> {
    super::sync::run()?;

    let repo_root = find_repo_root()?;

    let git_dir = repo_root.join(".git");
    let hooks_dir = git_dir.join("hooks");
    fs::create_dir_all(&hooks_dir)?;

    let post_commit_path = hooks_dir.join("post-commit");

    let existing_content = if post_commit_path.exists() {
        fs::read_to_string(&post_commit_path).ok()
    } else {
        None
    };

    let marker = "# Auto-generated by 'mt agent-config bootstrap'";

    if let Some(content) = &existing_content {
        if content.contains(marker) {
            println!(
                "Post-commit hook already installed at {}",
                post_commit_path.display()
            );
            return Ok(());
        }

        let new_content = format!("{}\n\n{}", content.trim_end(), POST_COMMIT_SCRIPT);
        fs::write(&post_commit_path, new_content)?;
    } else {
        fs::write(&post_commit_path, POST_COMMIT_SCRIPT)?;
    }

    let mut perms = fs::metadata(&post_commit_path)?.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&post_commit_path, perms)?;

    println!(
        "Installed post-commit hook at {}",
        post_commit_path.display()
    );

    Ok(())
}

fn find_repo_root() -> Result<PathBuf> {
    let home = std::env::var("HOME").context("HOME environment variable not set")?;
    let repo_root = PathBuf::from(&home).join("src").join("tools");

    if !repo_root.join("Cargo.toml").is_file() {
        anyhow::bail!(
            "{} に Cargo.toml が見つかりません。mt のソースリポジトリを {} に配置してください",
            repo_root.display(),
            repo_root.display()
        );
    }

    if !repo_root.join(".git").exists() {
        anyhow::bail!("{} に .git が見つかりません", repo_root.display());
    }

    Ok(repo_root)
}
