use anyhow::Result;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;

const POST_COMMIT_SCRIPT: &str = r#"#!/bin/sh
# Auto-generated by 'mt agent-config bootstrap'
# Syncs agent-configs to ~/.cursor/, ~/.claude/, ~/.config/opencode/ when agent-configs/ changes

changed_files=$(git diff-tree --no-commit-id --name-only -r HEAD)

if echo "$changed_files" | grep -q "^agent-configs/"; then
    echo "Detected changes in agent-configs/, syncing..."
    mt agent-config sync
fi
"#;

pub fn run() -> Result<()> {
    super::sync::run()?;

    let git_dir = find_git_dir()?;
    let hooks_dir = git_dir.join("hooks");
    fs::create_dir_all(&hooks_dir)?;

    let post_commit_path = hooks_dir.join("post-commit");

    let existing_content = if post_commit_path.exists() {
        fs::read_to_string(&post_commit_path).ok()
    } else {
        None
    };

    let marker = "# Auto-generated by 'mt agent-config bootstrap'";

    if let Some(content) = &existing_content {
        if content.contains(marker) {
            println!("Post-commit hook already installed at {}", post_commit_path.display());
            return Ok(());
        }

        let new_content = format!("{}\n\n{}", content.trim_end(), POST_COMMIT_SCRIPT);
        fs::write(&post_commit_path, new_content)?;
    } else {
        fs::write(&post_commit_path, POST_COMMIT_SCRIPT)?;
    }

    let mut perms = fs::metadata(&post_commit_path)?.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&post_commit_path, perms)?;

    println!("Installed post-commit hook at {}", post_commit_path.display());

    Ok(())
}

fn find_git_dir() -> Result<PathBuf> {
    let mut current = std::env::current_dir()?;

    loop {
        let git_dir = current.join(".git");
        if git_dir.exists() && git_dir.is_dir() {
            return Ok(git_dir);
        }

        if !current.pop() {
            anyhow::bail!("Not in a git repository");
        }
    }
}
