git:
  paging:
    pager: delta --dark --paging=never --line-numbers

gui:
  nerdFontsVersion: "3"
  showFileIcons: true
  language: en
  border: rounded
  theme:
    activeBorderColor: ["#89b4fa", "bold"]
  showFileTree: true
  expandFocusedSidePanel: true
