import type {
  WorkflowDef,
  CheckCtx,
  PromptCtx,
  CheckResult,
} from '../mt-workflow/types';
import { join } from 'node:path';

const def: WorkflowDef = {
  id: 'mt-propose-quality',

  steps: [
    {
      key: 'brainstorm',
      phase: 'ブレスト',
      type: 'task',
      maxRetries: 1,
      onFail: { action: 'escalate' },
      task: {
        action: 'orchestrate',
        buildPrompt: (ctx: PromptCtx) => {
          return [
            '## 目的',
            '',
            '対象 repo のコード品質を分析し、Quality 軸（既存の質の向上）の企画候補を 3 人の SubAgent で並列ブレストする。',
            '各 SubAgent は異なる視点で 5 案ずつ出し、合計 15 案を収集する。',
            '',
            '## 手順',
            '',
            '### 1. 対象 repo の確認',
            '',
            '```bash',
            'gh repo view --json nameWithOwner',
            '```',
            '',
            'ユーザーが特定のディレクトリ・モジュールを指定していれば走査範囲を絞る。',
            '',
            '### 2. 3 SubAgent 並列起動',
            '',
            'Task ツールで 3 人の SubAgent を同一メッセージで並列起動する。各 SubAgent に以下を指示する:',
            '',
            '- 対象 repo の品質分析（指定された視点に重点を置いて走査）',
            '- 5 案の企画候補を抽出',
            '- 各候補に「タイトル」「背景（根拠を織り込む）」「具体的なファイル・行・症状」を付与',
            '- 既存 open Issue を確認し、重複しそうな案は避ける（二重防御）',
            '- アーキテクチャ深化の重いテーマは背景に `mt-improve-codebase-architecture` 連携の注記を含める',
            '',
            '#### SubAgent 1: コードの健全性',
            '',
            '複雑度・浅い module・重複コード・エラーハンドリング・unwrap/パニックリスクの観点で 5 案。',
            '走査の優先度: 最近の変更が多い箇所（git log -30 で頻出パス）→ 長大ファイル → 重複パターン。',
            '',
            '#### SubAgent 2: テスト・検証の充実',
            '',
            'テスト不足・カバレッジの低い領域・テスト規約違反の観点で 5 案。',
            '走査の優先度: テストファイルが存在しない主要モジュール → テスト規約（README の Rule 等）との乖離。',
            '',
            '#### SubAgent 3: ドキュメント・保守性',
            '',
            'ドキュメント陳腐化・README と実装の乖離・TODO/FIXME の集積・依存の古さの観点で 5 案。',
            '走査の優先度: README のテーブルと実装の照合 → TODO/FIXME コメント → 非推奨 API の使用。',
            '',
            '### 3. 結果の集約',
            '',
            '3 人の SubAgent から返却された合計 15 案を 1 つのリストにまとめる。',
            '各候補に以下の情報を含める:',
            '- タイトル',
            '- 背景（根拠を織り込んだ 2〜3 文）',
            '- 具体的な根拠（ファイル・行・症状）',
            '- 視点（どの SubAgent の案か）',
            '',
            '集約結果をセッションディレクトリに `brainstorm-results.json` として保存する:',
            '',
            '```json',
            '{',
            '  "candidates": [',
            '    {',
            '      "id": 1,',
            '      "title": "...",',
            '      "background": "...",',
            '      "evidence": "...",',
            '      "perspective": "コードの健全性"',
            '    }',
            '  ]',
            '}',
            '```',
            '',
            '## セッション情報',
            '',
            `- セッションディレクトリ: ${ctx.sessionDir}`,
            '',
            '## 禁止事項',
            '',
            '- repo のファイルを変更しない（読み取り専用）',
            '- Issue を起票しない',
            '- 候補の水増しをしない（各 SubAgent ちょうど 5 案）',
          ].join('\n');
        },
      },
      check: (_ctx: CheckCtx): CheckResult => ({ status: 'pass', reasons: [] }),
    },

    {
      key: 'dedup_check',
      phase: '重複チェック',
      type: 'task',
      maxRetries: 1,
      onFail: { action: 'escalate' },
      task: {
        action: 'orchestrate',
        buildPrompt: (ctx: PromptCtx) => {
          return [
            '## 目的',
            '',
            'ブレストで収集した 15 案と既存の open Issue/計画を照合し、重複を除外または注記する。',
            '',
            '## 手順',
            '',
            '### 1. brainstorm-results.json の読み込み',
            '',
            `${ctx.sessionDir}/brainstorm-results.json から 15 案を読み込む。`,
            '',
            '### 2. 既存 Issue/計画の取得',
            '',
            '```bash',
            'gh issue list --state open --limit 100 --json number,title,labels',
            `bun ${join(import.meta.dir, '../mt-plan/list-plans.ts')} draft refined in-progress`,
            '```',
            '',
            '### 3. 照合・判定',
            '',
            '各候補を既存 Issue/計画のタイトルと照合する:',
            '',
            '- **同一テーマ**: 候補から除外し、除外理由を記録する',
            '- **関連テーマ**: 候補に残し「既存 Issue #N に関連」と注記する',
            '- **無関係**: そのまま候補に残す',
            '',
            '### 4. 結果の保存',
            '',
            `重複チェック後の候補リストを ${ctx.sessionDir}/dedup-results.json に保存する:`,
            '',
            '```json',
            '{',
            '  "candidates": [',
            '    {',
            '      "id": 1,',
            '      "title": "...",',
            '      "background": "...",',
            '      "evidence": "...",',
            '      "perspective": "...",',
            '      "note": "既存 Issue #N に関連"',
            '    }',
            '  ],',
            '  "excluded": [',
            '    { "id": 5, "title": "...", "reason": "Issue #N と同一テーマ" }',
            '  ]',
            '}',
            '```',
            '',
            '## セッション情報',
            '',
            `- セッションディレクトリ: ${ctx.sessionDir}`,
          ].join('\n');
        },
      },
      check: (_ctx: CheckCtx): CheckResult => ({ status: 'pass', reasons: [] }),
    },

    {
      key: 'review_score',
      phase: 'レビュー・採点',
      type: 'task',
      maxRetries: 1,
      onFail: { action: 'escalate' },
      task: {
        action: 'orchestrate',
        buildPrompt: (ctx: PromptCtx) => {
          return [
            '## 目的',
            '',
            '重複チェック後の候補（最大 15 案）を 3 人のレビュアー SubAgent で並列採点し、上位 5 案を選出する。',
            '',
            '## 手順',
            '',
            '### 1. dedup-results.json の読み込み',
            '',
            `${ctx.sessionDir}/dedup-results.json から候補リストを読み込む。`,
            '',
            '### 2. 3 レビュアー SubAgent 並列起動',
            '',
            'Task ツールで 3 人のレビュアーを同一メッセージで並列起動する。',
            '各レビュアーは自分の観点で全候補を 1〜5 点で採点する。',
            '',
            '#### レビュアー 1: 深刻度',
            '',
            '「放置した場合のリスク。バグ・パニック・データ損失・保守不能化の可能性」で採点。',
            '',
            '#### レビュアー 2: 修正容易性',
            '',
            '「少ない変更で改善できるか。大規模リファクタなしで着手できるか」で採点。',
            '',
            '#### レビュアー 3: 波及効果',
            '',
            '「その修正が他の改善の前提になるか。直すことで連鎖的に良くなるか」で採点。',
            '',
            '各レビュアーの返却形式:',
            '',
            '```json',
            '{',
            '  "criterion": "深刻度",',
            '  "scores": [',
            '    { "id": 1, "score": 4, "comment": "..." },',
            '    { "id": 2, "score": 3, "comment": "..." }',
            '  ]',
            '}',
            '```',
            '',
            '### 3. 集計・選出',
            '',
            '3 観点の合計点で降順ソートし、上位 5 案を選出する。',
            '同点の場合はレビュアーのコメントを添えてユーザーに最終判断を委ねる（present_gate で提示）。',
            '',
            '### 4. 結果の保存',
            '',
            `採点結果を ${ctx.sessionDir}/review-results.json に保存する:`,
            '',
            '```json',
            '{',
            '  "ranked": [',
            '    {',
            '      "id": 3,',
            '      "title": "...",',
            '      "background": "...",',
            '      "evidence": "...",',
            '      "note": "...",',
            '      "scores": { "深刻度": 4, "修正容易性": 5, "波及効果": 3 },',
            '      "total": 12,',
            '      "comments": { "深刻度": "...", "修正容易性": "...", "波及効果": "..." }',
            '    }',
            '  ]',
            '}',
            '```',
            '',
            '## セッション情報',
            '',
            `- セッションディレクトリ: ${ctx.sessionDir}`,
          ].join('\n');
        },
      },
      check: (_ctx: CheckCtx): CheckResult => ({ status: 'pass', reasons: [] }),
    },

    {
      key: 'present_gate',
      phase: '候補提示',
      type: 'human_gate',
      maxRetries: 1,
      onFail: { action: 'abort' },
      humanGate: {
        presentArtifacts: [],
        choices: [
          { value: 'approve', label: '選択した', desc: '起票する候補を選択した' },
          { value: 'abort', label: '中断', desc: '起票せず終了する' },
        ],
      },
      check: (_ctx: CheckCtx): CheckResult => ({ status: 'pass', reasons: [] }),
    },

    {
      key: 'create_drafts',
      phase: 'draft 起票',
      type: 'task',
      maxRetries: 1,
      onFail: { action: 'escalate' },
      task: {
        action: 'orchestrate',
        buildPrompt: (ctx: PromptCtx) => {
          return [
            '## 目的',
            '',
            'ユーザーが選択した候補を最小構成の draft Issue として起票する。',
            '',
            '## 手順',
            '',
            '### 1. label の確認・自動作成',
            '',
            '```bash',
            'gh label create "kind/plan" --repo <owner/repo> --color "0E8A16" --description "計画 Issue" 2>/dev/null || true',
            '```',
            '',
            '### 2. Issue 作成',
            '',
            '各選択候補について `gh issue create` で起票する。',
            '',
            '- **本文はタイトル + `## 💭 背景` のみの最小構成**とする。完了条件・方針・実行単位は書かない',
            '- 背景には走査根拠と企画の意図を自然に織り込む',
            '- アーキテクチャ深化を含む場合は背景に `mt-improve-codebase-architecture` 連携の注記を含める',
            '- 重複チェックで注記がある場合は背景末尾に `関連: #N` を追記する',
            '',
            '```bash',
            'gh issue create --repo <owner/repo> \\',
            '  --title "<タイトル>" \\',
            '  --body "## 💭 背景',
            '',
            '<背景本文（根拠を織り込む）>',
            '',
            '## 🐢 履歴',
            '" \\',
            '  --label "kind/plan"',
            '```',
            '',
            '### 3. Project 追加・Status 設定',
            '',
            '`~/.config/mt-plan/config.json` から `projectNumber`, `owner`, `statusFieldId`, `statusOptions.draft` を読み取り、Project に追加して Status を `draft` に設定する。',
            '',
            '```bash',
            'gh project item-add <projectNumber> --owner <owner> --url <issueUrl> --format json',
            'gh project item-edit --id <itemId> --field-id <statusFieldId> --single-select-option-id <draftOptionId>',
            '```',
            '',
            '### 4. 報告',
            '',
            '起票結果を報告する:',
            '- 各 Issue の URL、タイトル、Status',
            '- 起票しなかった候補の一覧',
            '- 次ステップの案内: 「具体化は `mt-create-plan` の from-Issue フローで取り込めます」',
            '',
            '## セッション情報',
            '',
            `- セッションディレクトリ: ${ctx.sessionDir}`,
            '',
            '## 禁止事項',
            '',
            '- ユーザーが選択しなかった候補を起票しない',
            '- 本文に完了条件・方針・実行単位を含めない',
          ].join('\n');
        },
      },
      check: (_ctx: CheckCtx): CheckResult => ({ status: 'pass', reasons: [] }),
    },

    {
      key: 'confirm_done',
      phase: '完了確認',
      type: 'human_gate',
      maxRetries: 1,
      onFail: { action: 'escalate' },
      humanGate: {
        presentArtifacts: [],
        choices: [
          { value: 'approve', label: 'Done', desc: '完了として終了する' },
          { value: 'abort', label: '中断' },
        ],
      },
      check: (_ctx: CheckCtx): CheckResult => ({ status: 'pass', reasons: [] }),
    },
  ],
};

export default def;
