use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use crate::cli::style;

use super::shared::{chezmoi_binary_present, home_dir};

/// Run `mt chezmoi doctor`: run chezmoi's own doctor first, then add
/// `mt`-specific checks for the source dir, age key, post-commit hook,
/// agent-configs/ removal, and platform-native hook placement.
pub fn run() -> anyhow::Result<()> {
    style::intro("mt chezmoi doctor");

    if !chezmoi_binary_present() {
        style::error("chezmoi バイナリが見つかりません");
        style::info("`mt tool install` を実行して chezmoi を導入してください");
        std::process::exit(1);
    }
    style::success("chezmoi バイナリ: 検出");

    let version = Command::new("chezmoi")
        .arg("--version")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output();
    if let Ok(out) = version
        && out.status.success()
    {
        let s = String::from_utf8_lossy(&out.stdout);
        let first = s.lines().next().unwrap_or("").trim();
        if !first.is_empty() {
            style::info(&format!("バージョン: {first}"));
        }
    }

    if let Err(err) = run_chezmoi_native_doctor() {
        style::warn(&format!(
            "chezmoi ネイティブ doctor で問題が見つかりました: {}",
            err
        ));
    }

    let home = home_dir()?;
    let mut all_ok = true;

    if check_source_dir_config().is_ok() {
        style::success("CHEZMOI_SOURCE_DIR / chezmoi.toml sourceDir: 設定済み");
    } else {
        all_ok = false;
    }

    if check_age_key().is_ok() {
        style::success("age 秘密鍵: 検出");
    } else {
        all_ok = false;
    }

    if check_post_commit_hook().is_ok() {
        style::success("post-commit hook: 設置済み");
    } else {
        style::warn("post-commit hook: 未設置（`mt chezmoi install-hook` で設置可能）");
    }

    if check_agent_configs_removed(&home).is_ok() {
        style::success("agent-configs/: 削除済み（chezmoi 移管完了）");
    } else {
        style::warn("agent-configs/: 残存しています。`rm -rf agent-configs/` で削除してください");
        all_ok = false;
    }

    if check_platform_settings(&home) {
        style::success("platform-native hook: 4 ファイル配置済み");
    } else {
        style::warn("platform-native hook: 一部未配置（`mt chezmoi install-hook` で再配置可能）");
        all_ok = false;
    }

    if check_agent_sync().is_ok() {
        style::success("agent/skill sync: 同期済み");
    } else {
        style::error("agent/skill sync: 未同期の項目があります。`mt agent sync` を実行してください");
        all_ok = false;
    }

    if all_ok {
        style::outro("doctor: すべての mt 固有チェック OK");
    } else {
        style::outro("doctor: 一部未設定項目あり。上のメッセージを参照してください");
        std::process::exit(2);
    }
    Ok(())
}

fn run_chezmoi_native_doctor() -> anyhow::Result<()> {
    let mut child = Command::new("chezmoi")
        .arg("doctor")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| anyhow::anyhow!("chezmoi doctor の起動に失敗しました: {e}"))?;

    if let Some(stdout) = child.stdout.take() {
        let reader = BufReader::new(stdout);
        for line in reader.lines().map_while(Result::ok) {
            println!("    {line}");
        }
    }
    let status = child
        .wait()
        .map_err(|e| anyhow::anyhow!("chezmoi doctor の終了待機に失敗しました: {e}"))?;
    if !status.success() {
        anyhow::bail!("chezmoi doctor が非ゼロで終了");
    }
    Ok(())
}

fn check_source_dir_config() -> anyhow::Result<()> {
    if std::env::var("CHEZMOI_SOURCE_DIR").is_ok() {
        return Ok(());
    }
    let home = home_dir()?;
    let config = home.join(".config").join("chezmoi").join("chezmoi.toml");
    if !config.is_file() {
        anyhow::bail!(
            "chezmoi.toml が見つかりません ({})。README のセットアップ手順を参照してください",
            config.display()
        );
    }
    let content = std::fs::read_to_string(&config)?;
    if !content.contains("sourceDir") {
        anyhow::bail!("chezmoi.toml に sourceDir が設定されていません");
    }
    Ok(())
}

fn check_age_key() -> anyhow::Result<()> {
    let home = home_dir()?;
    let key_path = home.join(".config").join("chezmoi").join("key.txt");
    if !key_path.is_file() {
        anyhow::bail!(
            "age 秘密鍵が見つかりません ({}): `age-keygen -o {}` で生成してください",
            key_path.display(),
            key_path.display()
        );
    }
    let content = std::fs::read_to_string(&key_path)?;
    if !content.contains("AGE-SECRET-KEY-") {
        anyhow::bail!(
            "{} の内容が age 秘密鍵として認識できません",
            key_path.display()
        );
    }
    Ok(())
}

fn check_post_commit_hook() -> anyhow::Result<()> {
    let home = home_dir()?;
    let tools_repo = home.join("src").join("tools");
    let post_commit = locate_post_commit_hook(&tools_repo)?;
    let content = std::fs::read_to_string(&post_commit)?;
    if content.contains("# Auto-generated by 'mt agent-config bootstrap'") {
        return Ok(());
    }
    if content.contains("# Auto-generated by 'mt chezmoi install-hook'") {
        return Ok(());
    }
    anyhow::bail!(
        "{} は mt 由来の post-commit hook として認識できません",
        post_commit.display()
    )
}

fn locate_post_commit_hook(tools_repo: &Path) -> anyhow::Result<std::path::PathBuf> {
    if !tools_repo.join("Cargo.toml").is_file() {
        anyhow::bail!("{} に Cargo.toml が見つかりません", tools_repo.display());
    }
    let candidate = tools_repo.join(".git").join("hooks").join("post-commit");
    if !candidate.is_file() {
        anyhow::bail!("post-commit hook が見つかりません: {}", candidate.display());
    }
    Ok(candidate)
}

fn check_agent_configs_removed(home: &Path) -> anyhow::Result<()> {
    let tools_repo = locate_tools_repo(home);
    let agent_configs = tools_repo.join("agent-configs");
    if agent_configs.is_dir() {
        anyhow::bail!("{} が残存しています", agent_configs.display());
    }
    Ok(())
}

fn check_agent_sync() -> anyhow::Result<()> {
    let source_dir = crate::agent::shared::chezmoi_source_dir()?;
    match crate::agent::shared::check_sync_status(&source_dir)? {
        None => Ok(()),
        Some(issues) => {
            eprintln!("{}", issues);
            anyhow::bail!("agent/skill 未同期")
        }
    }
}

fn locate_tools_repo(home: &Path) -> std::path::PathBuf {
    if let Ok(source) = std::env::var("CHEZMOI_SOURCE_DIR")
        && !source.is_empty()
    {
        let p = std::path::PathBuf::from(&source);
        if let Some(parent) = p.parent() {
            return parent.to_path_buf();
        }
    }
    home.join("src").join("tools")
}

fn check_platform_settings(home: &Path) -> bool {
    let checks: &[(&str, PathBuf)] = &[
        ("Cursor hooks.json", home.join(".cursor/hooks.json")),
        ("Claude settings.json", home.join(".claude/settings.json")),
        (
            "opencode bridge",
            home.join(".config/opencode/plugins/cursor-hook-bridge.ts"),
        ),
        (
            "共通 hook スクリプト",
            home.join(".config/opencode/plugins/agent-hooks/block-cursor-config-direct-edit.ts"),
        ),
    ];

    let mut all_ok = true;
    for (label, path) in checks {
        if !path.exists() {
            style::warn(&format!(
                "platform hook {}: 未配置 ({})",
                label,
                path.display()
            ));
            all_ok = false;
        }
    }
    all_ok
}

#[cfg(test)]
#[path = "doctor.test.rs"]
mod tests;
